version: '3.7'

services:
  school-mysql:
    container_name: school-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: schoolRegistry
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - school_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - school-network

  school-phpmyadmin:
    container_name: school-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - school-mysql
    environment:
      PMA_HOST: school-mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - school-network

  school-backend:
    container_name: school-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - school-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://school-mysql:3306/schoolRegistry
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "8080:8080"
    networks:
      - school-network

  school-frontend:
    container_name: school-frontend
    image: vvenegasdev/front-school:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - school-backend
    networks:
      - school-network

volumes:
  school_mysql_data:

networks:
  school-network:
